Replace c99_math.h with the standard math.h
c99_math.h #defines a signbit() macro, but this macro clobbers use of
std::signbit() in clang's C++20 header files. We compile glsl-optimizer
as C11 and C++, so we no longer need any of c99_math.h's C99 polyfill
implementations. We can just use C's standard math.h.

In file included from glsl-optimizer/src/compiler/glsl/lower_precision.cpp:37:
In file included from /Users/chris/.mozbuild/clang/bin/../include/c++/v1/vector:274:
In file included from /Users/chris/.mozbuild/clang/bin/../include/c++/v1/__bit_reference:15:
In file included from /Users/chris/.mozbuild/clang/bin/../include/c++/v1/algorithm:667:
In file included from /Users/chris/.mozbuild/clang/bin/../include/c++/v1/functional:493:
In file included from /Users/chris/.mozbuild/clang/bin/../include/c++/v1/__algorithm/search.h:16:
In file included from /Users/chris/.mozbuild/clang/bin/../include/c++/v1/utility:236:
In file included from /Users/chris/.mozbuild/clang/bin/../include/c++/v1/compare:144:
In file included from /Users/chris/.mozbuild/clang/bin/../include/c++/v1/__compare/compare_partial_order_fallback.h:13:
In file included from /Users/chris/.mozbuild/clang/bin/../include/c++/v1/__compare/partial_order.h:14:
In file included from /Users/chris/.mozbuild/clang/bin/../include/c++/v1/__compare/weak_order.h:14:
Users/chris/.mozbuild/clang/bin/../include/c++/v1/__compare/strong_order.h:68:35: error: expected unqualified-id
return _VSTD::signbit(__u) <=> _VSTD::signbit(__t);
              ^
glsl-optimizer/include/c99_math.h:123:20: note: expanded from macro 'signbit'
define signbit(x) ((x) < 0.0f)