Rename glsl-optimizer's unreachable() macro to GLSL_UNREACHABLE()
glsl-optimizer's macros.h #defines a macro called unreachable() whose name conflicts with C++23's new std::unreachable() function declaration in the <utility> std library header.

https://en.cppreference.com/w/cpp/utility/unreachable

warning: ~/.mozbuild/MacOSX14.2.sdk/usr/include/c++/v1/__utility/unreachable.h:28:48: error: expected unqualified-id
warning:    28 | [[noreturn]] _LIBCPP_HIDE_FROM_ABI inline void unreachable() { __libcpp_unreachable(); }
warning: third_party/rust/glslopt/glsl-optimizer/src/util/macros.h:76:29: note: expanded from macro 'unreachable'
warning:    76 | #define unreachable(str)